# Use root/example as user/password credentials
services:
  mongo:
    image: mongo
    ports:
    - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: zynk
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 80:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: zynk
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: zynk
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://zynk:example@mongo:27017/
